/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   mini_signals.c                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jnenczak <jnenczak@student.42roma.it>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/02/12 17:03:22 by jnenczak          #+#    #+#             */
/*   Updated: 2025/02/12 17:04:15 by jnenczak         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <mini_base.h>

/**
 * @brief Signal handler for SIGINT (Ctrl+C).
 *
 * This function is called when the SIGINT
 * signal is received. It writes a 
 * newline character to the standard output,
 * resets the readline library's 
 * input line, and redisplays the prompt.
 *
 * @param sig The signal number (unused).
 */
static void	signals_handle_sigint(int sig)
{
	(void)sig;
	write(1, "\n", 1);
	rl_on_new_line();
	rl_replace_line("", 0);
	rl_redisplay();
}

/**
 * @brief Sets up signal handlers for the application.
 *
 * This function configures the signal handlers for SIGINT and SIGQUIT signals.
 * - SIGINT: When the SIGINT signal is received
 * (typically generated by pressing Ctrl+C),
 *   the `signals_handle_sigint` function will be
 * called to handle the signal.
 * - SIGQUIT: The SIGQUIT signal (typically generated
 * by pressing Ctrl+\) will be ignored.
 */
void	signals_setup(void)
{
	signal(SIGINT, signals_handle_sigint);
	signal(SIGQUIT, SIG_IGN);
}
